version: "3.7"
services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
      MYSQL_USER: "todo_user"
      MYSQL_PASSWORD: "todo_password"
      MYSQL_DATABASE: "todo"
    volumes:
      - mariadb_volume:/var/lib/mysql
    ports:
      - "127.0.0.1:3307:3306"
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "81:80"

volumes:
  mariadb_volume:
